apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../_bases/infrastructure/apps/

commonLabels:
  app: demo-infrastructure

nameSuffix: '-demo'

resources:
  - demo-rabbitmq-application.yml