apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-rabbitmq
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  source:
    repoURL: git@github.com:dmfrey/demo-parent-gitops.git
    targetRevision: HEAD
    path: charts/infrastructure-rabbitmq
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
