apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../_bases/schema-registry/

commonLabels:
  namespace: demo

nameSuffix: '-demo'

patchesStrategicMerge:
  - root.yml
