apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-app-root
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  project: demo
  source:
    repoURL: git@github.com:dmfrey/demo-parent-gitops.git
    targetRevision: HEAD
    path: argocd/order-app/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd