apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: person-app-root
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: dev
  source:
    repoURL: git@github.com:dmfrey/demo-parent-gitops.git
    targetRevision: HEAD
    path: argocd/demo-ns-overlays/person-app/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
