apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../_bases/person-app/apps/

commonLabels:
  namespace: demo

nameSuffix: '-demo'

patchesStrategicMerge:
  - person-app-db-application.yml
  - person-app-service-application.yml
