---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: {{ .Values.serviceAccount.roleBinding.name }}
  namespace: {{ .Release.Namespace }}

subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}

roleRef:
  kind: ClusterRole
  name: {{ .Values.serviceAccount.clusterRole.name }}
  apiGroup: ""
