apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-app
  namespace: argocd
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
  project: demo
  source:
    repoURL: git@github.com:dmfrey/demo-parent-gitops.git
    targetRevision: HEAD
    path: charts/order-app
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo