apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: person-app-root
  namespace: argocd
spec:
  source:
    repoURL: git@github.com:dmfrey/demo-parent-gitops.git
    targetRevision: HEAD
    path: argocd/_bases/person-app/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd