apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-app-db
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
  project: dev
  source:
    repoURL: git@github.com:dmfrey/demo-parent-gitops.git
    targetRevision: HEAD
    path: charts/order-app-db
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
      values: |
        spec:
          pgConfig:
            dbname: order_app_dev_db
            username: order_app_dev_db_admin
            appUser: order_app_dev_db_user
  destination:
    server: https://kubernetes.default.svc
    namespace: dev