apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: order-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: dev
  source:
    repoURL: git@github.com:dmfrey/demo-parent-gitops.git
    targetRevision: HEAD
    path: charts/order-app
    helm:
      ignoreMissingValueFiles: true
      valueFiles:
        - values.yaml
      values: |
        serviceAccount:
          name: order-app-dev-sa
          clusterRole:
            name: "order-app-dev-cluster-role-namespace-reader"
          roleBinding:
            name: "order-app-dev-namespace-reader-binding"
        serviceBinding:
          postgres:
            secretName: order-app-db-dev-app-user-db-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
